// Code generated by goyacc -l -o parser.go parser.y. DO NOT EDIT.
package pg

import __yyfmt__ "fmt"

type pair struct {
	key string
	val interface{}
}

func setResult(l yyLexer, v string) {
	l.(*lex).result = v
}

type yySymType struct {
	yys  int
	obj  map[string]interface{}
	list []interface{}
	pair pair
	val  interface{}
	str  string
}
